services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null
    container_name: image-api
    volumes:
      - ./src:/app/src
      - ./deno.json:/app/deno.json
      - ./deno.lock:/app/deno.lock
    ports:
      - "${PORT}:4000"
    env_file:
      - .env
    networks:
      - servant-network
    restart: unless-stopped

networks:
  servant-network:
    external: true
