services:
  app:
    container_name: image-api
    env_file:
      - .env
    image: ghcr.io/tancred423/image-api:latest
    ports:
      - "${PORT}:4000"
    volumes:
      - ./images:/app/src/images
    networks:
      - servant-network
    restart: unless-stopped

networks:
  servant-network:
    external: true
